### ISSUE TITLE
Why is start_of_episode = False when env is reset?

### ISSUE THREAD

**Issue by raymondchua** [google-deepmind/dqn_zoo#26]
Hi, 
Can someone explain why the start of the episode is false when the GymAtari environment is reseted? 
Shouldn't it be true?

https://github.com/google-deepmind/dqn_zoo/blob/8728c674420725f49f6dec9b893f9420fd5cd2ef/dqn_zoo/gym_atari.py#L77C1-L77C1

**Comment by jqdm** [comment]
The line

```python
self._start_of_episode = False
```

is set at the end of `reset()` to indicate to the next call to `step()` is no longer the start of the episode; we have returned the first timestep. The comments [here](https://github.com/google-deepmind/dqn_zoo/blob/8728c674420725f49f6dec9b893f9420fd5cd2ef/dqn_zoo/gym_atari.py#L82-L84) explains in more detail why this internal variable exists.
